// This file is autogenerated. Changes will be overwritten.
#include "WGLTATH3HH/moc_MainWindow.cpp"
#include "WGLTATH3HH/moc_MyDatatables.cpp"
#include "WGLTATH3HH/moc_MyLanguageModel.cpp"
#include "WGLTATH3HH/moc_MyOrgSettings.cpp"
